### ISSUE TITLE
Unable to interact with alternate oci tags

### ISSUE THREAD

**Issue by zack-is-cool** [defenseunicorns/uds-cli#331]
### Environment

Device and OS:  macos 14
App version: v0.6.1
Kubernetes distro being used: n/a
Other:

### Steps to reproduce

Using a UDS package, I'm unable to interact with it using alternate tags other than the one it was published as initially
https://github.com/defenseunicorns/uds-core/pkgs/container/packages%2Fuds%2Fbundles%2Fk3d-core/167697356?tag=0.8.0-amd64

I tried using the other tag of amd64 and also the sha256 of the artifact

```bash
[root@ip-10-200-37-125 ~]# uds pull oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core:0.8.0-am
d64

 NOTE  Saving log file to /tmp/uds-2024-01-17-20-25-06-2772045480.log
  ✔  Verified uds-k3d-dev package                                                                       
     ERROR:  execution cancelled due to an interrupt                                                    
    Verifying layers in Zarf package: init ███████████████████████████████████████████████  21% | 2s[root@ip-10-200-37-125 ~]# ^C

[root@ip-10-200-37-125 ~]# uds pull oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core:amd64

 NOTE  Saving log file to /tmp/uds-2024-01-17-20-25-18-2963618043.log
  ✔  Waiting for cluster connection (30s timeout)                                                       
     ERROR:  oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core:amd64: not found

[root@ip-10-200-37-125 ~]# uds pull oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core@sha256:209caf0df45f495f09616b187a5e8a05e79be5a8481d904b2a001e9c569f918c

 NOTE  Saving log file to /tmp/uds-2024-01-17-20-26-47-48801956.log
  ✔  Waiting for cluster connection (30s timeout)                                                       
     ERROR:  oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core@sha256:209caf0df45f495f09616b187a5e8a05e79be5a8481d904b2a001e9c569f918c:
             not found
```

### Expected result

Be able to use other tags

### Actual Result

Errors out, not found.

**Comment by UncleGedd** [comment]
Thanks for this @zack-is-cool , we'll prioritize multi-arch support in UDS CLI

**Comment by mjnagel** [comment]
I think the problem with the way we are doing this is this specific line - https://github.com/defenseunicorns/uds-cli/blob/main/src/pkg/bundle/remote.go#L261 . If a tag is published without architecture or with just the architecture (as in the above example) it wouldn't be supported by a `uds deploy`.

**Comment by UncleGedd** [comment]
Yeah there's a couple of threads to pull here:
- For sure that line you referenced is an issue because today UDS CLI is opinionated on its tag format
- The more pressing issue is that to actually support multi-arch OCI repos as per the [spec](https://github.com/opencontainers/image-spec/blob/main/image-index.md), we need to modify the way that our `index.json` points to UDS bundle root manifests. True multi-arch support means that our OCI repos' `index.json` can contain pointers to multiple bundle root manifests, and therefore multiple platforms/arches in the same OCI repo. This is particularly important if you want to use the `latest` tag as opposed to `amd64` or `arm64`, and have UDS CLI figure out the arch based on the system or `-a` flag

**Comment by UncleGedd** [comment]
Fixed with https://github.com/defenseunicorns/uds-cli/pull/352
