### ISSUE TITLE
When `zarf` isn't on path, actions in packages with `./zarf` fail

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-cli#45]
Easiest example being the zarf init package, relevant yaml [here](https://github.com/defenseunicorns/zarf/blob/main/packages/zarf-registry/zarf.yaml#L133-L141)

**Comment by corang** [comment]
Bandaid for now is to make sure the zarf executable is on path

**Comment by corang** [comment]
@Noxsios @Racer159 @UncleGedd 
Want to have a discussion about making this less painful for applications that use zarf. My thought is to convert any action that uses `./zarf` into an internal function call instead of literally calling the binary again

**Comment by zachariahmiller** [comment]
This was also the case in the testing i did on windows. 

`My thought is to convert any action that uses ./zarf into an internal function call instead of literally calling the binary again` 

^this would be great

**Comment by Noxsios** [comment]
Note: this behavior only exists if `os.Executable` does not fail and Zarf is being used as a library.

**Comment by Racer159** [comment]
It would be difficult to do it as an internal call since `./zarf` could be anywhere inside of a script expression (e.g. inside of a shell `if` statement) meaning you would need to integrate that logic with the shell somehow still.  The easiest way to do it if you didn't want all of Zarf's commands to be mixed / available to uds cli would be with an internal hidden command that exposed Zarf's commands (like Zarf has for `zarf internal`).

Zarf could also have something like `zarf:` instead of `cmd:` that would let you execute single zarf commands internally but that would not be usable with other shell logic and wouldn't really bring new functionality.

**Comment by UncleGedd** [comment]
Completed with: https://github.com/defenseunicorns/uds-cli/pull/299
